INSERT INTO neighborhoods (name)
VALUES
    ('Acorn Industrial'),
    ('Acorn'),
    ('Adams Point'),
    ('Allendale'),
    ('Arroyo Viejo'),
    ('Bartlett'),
    ('Bella Vista'),
    ('Beulah Heights'),
    ('Broadway Valdez District Specific Plan'),
    ('Brookfield Village'),
    ('Bushrod Neighborhood'),
    ('Caballo Hills'),
    ('Castlemont'),
    ('Chabot Park'),
    ('Chinatown'),
    ('City Center'),
    ('Civic Center'),
    ('Claremont Hills'),
    ('Clawson'),
    ('Cleveland Heights'),
    ('Clinton'),
    ('Coliseum'),
    ('Coliseum Industrial'),
    ('Columbia Gardens'),
    ('Columbia Park'),
    ('Cox'),
    ('Crestmont'),
    ('Crocker Highlands'),
    ('Dimond District'),
    ('Dogtown'),
    ('Downtown Oakland'),
    ('Durant Manor'),
    ('Eastmont'),
    ('Eastmont Hills'),
    ('East Peralta'),
    ('Edgewater'),
    ('Elmhurst Park'),
    ('Embarcadero'),
    ('Fairfax'),
    ('Fairview Park'),
    ('Fitchburg'),
    ('Foothill Square'),
    ('Forestland'),
    ('Fremont'),
    ('Frick'),
    ('Fruitvale Station'),
    ('Gaskill'),
    ('Ghosttown'),
    ('Glen Echo'),
    ('Glen Highlands'),
    ('Glenview'),
    ('Golden Gate'),
    ('Grand Lake'),
    ('Grass Valley'),
    ('Haddon Hill'),
    ('Harrington'),
    ('Havenscourt'),
    ('Highland'),
    ('Highland Park'),
    ('Highland Terrace'),
    ('Hiller Highlands'),
    ('Holy Names University'),
    ('Hoover-Foster'),
    ('Iveywood'),
    ('Ivy Hill'),
    ('Jack London Square'),
    ('JAMMMI'),
    ('Jefferson'),
    ('Jingletown'),
    ('Joaquin Miller Park'),
    ('Koreantown Northgate'),
    ('Lakeshore'),
    ('Lakeside'),
    ('Laney College'),
    ('Las Palmas'),
    ('Leona Heights'),
    ('Lincoln Highlands'),
    ('Lincoln Square'),
    ('Lockwood-Tevis'),
    ('Longfellow'),
    ('Lower Bottoms'),
    ('Lower Dimond'),
    ('Lower Rockridge'),
    ('Lynn'),
    ('Maxwell Park'),
    ('McClymonds'),
    ('Melrose'),
    ('Melrose Heights'),
    ('Merriewood'),
    ('Merritt'),
    ('Mills College'),
    ('Millsmont'),
    ('Montclair'),
    ('Montclair Village'),
    ('Mosswood'),
    ('Mountain View Cemetery'),
    ('Neighborhood Groups'),
    ('NOBE'),
    ('Northgate'),
    ('North Oakland'),
    ('North Stonehurst'),
    ('Oak Center'),
    ('Oak Knoll'),
    ('Oakland Airport'),
    ('Oakland Avenue'),
    ('Oakmore Highlands'),
    ('Oak Tree'),
    ('Old Oakland'),
    ('Panoramic Hill'),
    ('Paradise Park'),
    ('Parkridge Estates'),
    ('Patten'),
    ('Peralta Hacienda'),
    ('Piedmont Avenue'),
    ('Piedmont Pines'),
    ('Pill Hill'),
    ('Prescott'),
    ('Public Safety Groups'),
    ('Ralph Bunche'),
    ('Rancho San Antonio'),
    ('Redwood Heights'),
    ('Reservoir Hill'),
    ('Rockridge'),
    ('San Pablo Gateway'),
    ('Santa Fe'),
    ('Sausal Creek'),
    ('School'),
    ('Seminary'),
    ('Sequoyah'),
    ('Sheffield Village'),
    ('Shepherd Canyon'),
    ('Skyline-Hillcrest Estates'),
    ('Sobrante Park'),
    ('South Kennedy Tract'),
    ('South Prescott'),
    ('South Stonehurst'),
    ('Spencer'),
    ('Saint Elizabeth'),
    ('Temescal'),
    ('The Jewel Box'),
    ('The Laurel District'),
    ('The TreeHouse'),
    ('The Twomps'),
    ('Toler Heights'),
    ('Trestle Glen'),
    ('Tuxedo'),
    ('Upper Dimond'),
    ('Upper Rockridge'),
    ('Uptown'),
    ('Vernon Heights'),
    ('Village Bottoms'),
    ('Waverly'),
    ('Webster'),
    ('Wenwrtoh Holland'),
    ('West Oakland'),
    ('Wilshire Heights'),
    ('Woodland'),
    ('Woodminster')
;

INSERT INTO residents (id, first_name, last_name, email, password, street, zipCode, is_volunteer, neighborhood)
VALUES
    (1, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '5000 MacArthur Blvd',94613, false, 'Mills College'),
    (2, 'Devan', 'Kumar', 'kumar.deva@northeastern.edu', 'miss27ouri', '4341 Davis Street',94601, false, 'Harrington'),
    (3, 'Matthew', 'Shi', 'shi.mat@northeastern.edu', 'vintage1092', '1506 Linden Street', 94607, true, 'Oak Center'),
    (4, 'Ashwin', 'Iyer', 'iyer.ashw@northeastern.edu', 'minne2311', '2281 E 10th Street', 94601, true, 'Prescott'),
    (5, 'Baoren', 'Liu', 'liu.baor@northeastern.edu', 'kansl1865', '5567 Carlton Street', 94618, true, 'Rockridge'),
    (6, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '85 Glen Avenue', 94611, true, 'Piedmont Avenue'),
    (7, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '3873 Rhoda Avenue', 94602, false, 'Upper Dimond'),
    (8, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '7945 Sunkist Drive', 94605, true, 'Eastmont Hills'),
    (9, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '7616 Weld Street', 94621, false, 'Arroyo Viejo'),
    (10, 'Jordan', 'Pinnick', 'pinnick.j@northeastern.edu', 'hello2F4', '1306 31st Avenue', 94601, false, 'Fruitvale')
